### ISSUE TITLE
Possible issue related to checking `skimr` version

### ISSUE THREAD

**Issue by GegznaV** [IndrajeetPatil/groupedstats#1]
I can be wrong, but I see a possible issue here: https://github.com/IndrajeetPatil/groupedstats/commit/b226010f9fb91361ccda49e74ccc25e6f26d9009#r32013461

**Comment by IndrajeetPatil** [comment]
See my reply.

**Comment by GegznaV** [comment]
Have you tried to use `<`? It is applicable in this situation, indeed. Find an example here: https://dplyr.tidyverse.org/articles/compatibility.html

**Comment by GegznaV** [comment]
If possible, I suggest not limiting the users of your package to `skimr` v2 after it is released, as this may break the code of old analyses.

**Comment by IndrajeetPatil** [comment]
Hah, I will be damned! I had no idea the return from `packageVersion()` function is of class ``"package_version"`. I will modify the code. Thanks for pressing me on this point!
