### ISSUE TITLE
Skimr V2 release is coming

### ISSUE THREAD

**Issue by elinw** [IndrajeetPatil/groupedstats#16]
I know you already updated for skimr v2 but I think you will probably want to change the minimum version.

**Comment by IndrajeetPatil** [comment]
Closed in https://github.com/IndrajeetPatil/groupedstats/commit/6208816d097cbb939c5746950c3d3ca73d564b44 and https://github.com/IndrajeetPatil/groupedstats/commit/0cd2c8e06b8f6c829c2aed25d3e72b32efc882c2
