### ISSUE TITLE
Skimr issues?

### ISSUE THREAD

**Issue by elinw** [IndrajeetPatil/groupedstats#17]
Hi,

We submitted skimr V2 to CRAN but apparently it is breaking the release of groupedstats.  I see you have already addressed this in your repo here, are you going to release to CRAN soon? I can write a note back to the CRAN people about it.
Thanks!
@IndrajeetPatil 
@michaelquinn32

**Comment by IndrajeetPatil** [comment]
Hi,

Yes, please write to them that you have already informed the package maintainer.

I'll be submitting a new version as soon as `skimr 2.0` is on `CRAN`.

Thanks!

**Comment by elinw** [comment]
Thanks!

**Comment by elinw** [comment]
Version 2 is now on CRAN.
