### ISSUE TITLE
p value methods

### ISSUE THREAD

**Issue by Benambridge** [IndrajeetPatil/groupedstats#20]
Thanks very much for this package! I'm sorry if this is covered somewhere in the documentation (I couldn't find it), but is there a way to control the method used to calculate the p values? I prefer to use the likelihood ratio test method outlined here [http://talklab.psy.gla.ac.uk/KeepItMaximalR2.pdf] but (a) I don't think there's a way to do this in lmerTest (as I understand it, it implements drop1 differently to lme4) and (b) if there is, I don't know how I would ensure that it's these p values that are passed to ggstatsplot? Thanks! Ben

**Comment by IndrajeetPatil** [comment]
The documentation now just points to `parameters::p_value`, which has more info: https://github.com/IndrajeetPatil/groupedstats/commit/a9b03a44af7123e4f38f69a6e869bd1e4e6b8143
