### ISSUE TITLE
grouped_lm does not return "id"/"key" column in output = "augment" 

### ISSUE THREAD

**Issue by gopi2904** [IndrajeetPatil/groupedstats#26]
Can the funtion grouped_lm with output = "augment" be augmented to return the "keys/ids". This would help in further joining the output with other tables.

**Comment by IndrajeetPatil** [comment]
This repo is actually no longer active development for the following reasons:

<img width="867" alt="Screenshot 2020-11-05 at 19 56 28" src="https://user-images.githubusercontent.com/11330453/98284215-13f5be80-1fa1-11eb-8353-130f55305971.png">

I would highly recommend you to use the `dplyr::group_modify` + `broom::tidy` workflow to do this kind of analysis.

e.g.,
```r
iris %>%
    group_by(Species) %>%
    group_modify(~ broom::tidy(lm(Petal.Length ~ Sepal.Length, data = .x)))
```
