### ISSUE TITLE
p value formatting for small p's is incorrect

### ISSUE THREAD

**Issue by GegznaV** [IndrajeetPatil/groupedstats#5]
Issue #4 is not solved yet but it is closed. Some ideas towards solving the issue:
1) https://scales.r-lib.org/reference/pvalue_format.html as **ggplot2** depends on **scales** no extra dependencies would be needed.
2) kassambara/ggpubr#186 (some extra ideas on the same topic of p-value formatting).

**Comment by IndrajeetPatil** [comment]
closed in favor of re-opening #4
